apiVersion: v1
kind: Pod
metadata:
  name: "flask-api-client"
  labels:
    demo: test
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: test-api
      image: alpine
      command: ['sh']
      args: ['-c', '/scripts/test.sh']
      volumeMounts:
      - name: scripts
        mountPath: /scripts
      env:
        - name: API_ENDPOINT
          value: https://flaskredis-python-flask-redis:4996
  volumes:
  - name: scripts
    configMap:
      name: test-api-scripts
      defaultMode: 511
  restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-api-scripts
data:
  test.sh: |
    set -xe
    function check_res_code {
        if [[ 200 != "$1" ]]; then
           echo "request failed with response code: $RES"
           exit 1;
        fi
    }
    apk add curl
    echo "sending requests to $API_ENDPOINT"
    PID=$RANDOM$RANDOM$RANDOM
    RES=$(curl -k -o /dev/null -s -w "%{http_code}\n" -X POST $API_ENDPOINT/client/client_$PID -d "fname=Jane&lname=Doe&address='123 Main Street'&city=Richmond&iban=DE12345678&ssn=123-223-2345&email=nr@aaa.com'")
    check_res_code $RES
    RES=$(curl -k -o /dev/null -s -w "%{http_code}\n" -X GET $API_ENDPOINT/client/client_$PID)
    check_res_code $RES
    RES=$(curl -k -o /dev/null -s -w "%{http_code}\n" -X GET $API_ENDPOINT/score/client_$PID)
    check_res_code $RES
    curl -k -X GET $API_ENDPOINT/client/client_$PID
    # curl -k -X GET $API_ENDPOINT/memory
